# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d9a4c8f89b71dc18d6adf09a6ce63bd60099e9c2a11250a20b85a51cefe47d687ef8760433dc471547c2a91bd76be18389ba5eb1cbcffb2fa11fc23d89b158

test:
  secret_key_base: 9737adefbf73515864f95e993004a3e33a54842b0bb190b5020e88e47dc7fb81a5bc56861853cd2763fb5062cbd1a28f58bb3084bf9cbeee7deae51523df4ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
